version: '3.8'

services:
  # Entorno de Ciencia de Datos y Python
  jupyterlab:
    image: jupyter/datascience-notebook:latest
    container_name: jupyterlab
    restart: always
    ports:
      - "8888:8888"
    environment:
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
    volumes:
      - jupyter_data:/home/jovyan/work

  # Motor de Automatización
  n8n:
    image: docker.n8n.io/n8nio/n8n:latest
    container_name: n8n_app
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - N8N_PROTOCOL=https
      - N8N_HOST=${DOMAIN_NAME}
      - WEBHOOK_URL=https://${DOMAIN_NAME}/
      - N8N_PORT=5678
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  jupyter_data:
  n8n_data: